//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDEntities : DbContext
    {
        private static GIBDDEntities _context;
        public GIBDDEntities()
            : base("name=GIBDDEntities")
        {
        }

        public static GIBDDEntities GetContext
        {
            get
            {
                if (_context == null)
                    _context = new GIBDDEntities();
                return _context;
            }
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auth> Auth { get; set; }
        public virtual DbSet<Car> Car { get; set; }
        public virtual DbSet<CarModel> CarModel { get; set; }
        public virtual DbSet<CarSpecification> CarSpecification { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CategoryOfLicense> CategoryOfLicense { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<DriverLicense> DriverLicense { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<Manufacter> Manufacter { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfDrive> TypeOfDrive { get; set; }
        public virtual DbSet<TypeOfDriveOfCar> TypeOfDriveOfCar { get; set; }
    }
}
