//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryOfLicense
    {
        public int LicenseId { get; set; }
        public int CategoryId { get; set; }
        public string Nothing { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DriverLicense DriverLicense { get; set; }
    }
}
