//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverLicense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverLicense()
        {
            this.CategoryOfLicense = new HashSet<CategoryOfLicense>();
        }
    
        public int Id { get; set; }
        public int DriverGUID { get; set; }
        public System.DateTime LicenseDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public string LicenseSeries { get; set; }
        public int LicenseNumber { get; set; }
        public int StatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOfLicense> CategoryOfLicense { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Status Status { get; set; }
    }
}
