//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDDApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfDriveOfCar
    {
        public int CarSpecId { get; set; }
        public int TypeOfDriveId { get; set; }
        public string Nothing { get; set; }
    
        public virtual CarSpecification CarSpecification { get; set; }
        public virtual TypeOfDrive TypeOfDrive { get; set; }
    }
}
